-- Crisis Options: Auto-generated from crisis-events.json
-- Crisis ID mapping:
--   1 = china-civil-war (1946) - 🇨🇳 Chinese Civil War Intensifies
--   2 = india-partition (1947) - 🇮🇳 India Partition Crisis
--   3 = argentina-peronism (1946) - 🇦🇷 Perón's Economic Revolution
--   4 = first-indochina-war (1946) - 🇻🇳 First Indochina War
--   5 = berlin-blockade (1948) - 🚨 Berlin Blockade Crisis
--   6 = marshall-plan (1948) - 💰 Marshall Plan Announced
--   7 = korean-war (1950) - 🇰🇷 Korean War Erupts
--   8 = argentina-british-debt (1947) - 🇦🇷 British Debt to Argentina
--   9 = argentina-commodity-boom (1948) - 🌾 Global Commodity Price Surge
--   10 = argentina-drought-1951 (1951) - 🌵 Argentine Drought Crisis
--   11 = evita-death-1952 (1952) - ⚫ Death of Eva Perón

-- Clear existing data and repopulate
TRUNCATE TABLE crisis_options;

INSERT INTO crisis_options (crisis_id, country_code, option_key, option_text, cost, effects, military_required, outcome) VALUES (1, 'China', 'kmt-offensive', '🪖 Launch Major Offensive Against Communists', 800, '{"gdpGrowth":-3,"inflation":50,"unemployment":2}', '{"army":1500000}', 'All-out war devastates the economy. Cities change hands repeatedly. Foreign backers are drawn deeper — USA pressured to increase aid shipments, USSR forced to counter-supply CCP. Delays communist victory but destruction is catastrophic.');
INSERT INTO crisis_options (crisis_id, country_code, option_key, option_text, cost, effects, military_required, outcome) VALUES (1, 'China', 'negotiate-coalition', '🤝 Negotiate Coalition Government', 0, '{"gdpGrowth":-0.5,"diplomaticPoints":8}', NULL, 'Mao uses ceasefire to consolidate rural bases. But the breathing room lets civilians evacuate cities and foreign observers praise the attempt. India and UK welcome the diplomacy. Communists still prepare their final offensive, but the world sees China tried peace first.');
INSERT INTO crisis_options (crisis_id, country_code, option_key, option_text, cost, effects, military_required, outcome) VALUES (1, 'USA', 'massive-aid', '💰 Massive Military Aid to Nationalists ($2B)', 2000, '{"tradeBalance":-2000,"diplomaticPoints":10}', NULL, 'Nationalist corruption wastes much of the aid, but the sheer scale forces Stalin to match it or look weak. Soviet Politburo hawks demand counter-escalation — draining USSR resources. Allied nations are reassured by American resolve. India gains leverage as a non-aligned mediator. The war grinds on longer, devastating China\'s economy further, but containment credibility is preserved.');
INSERT INTO crisis_options (crisis_id, country_code, option_key, option_text, cost, effects, military_required, outcome) VALUES (1, 'USA', 'disengage', '🏳️ Withdraw Support — Accept the Inevitable', 0, '{"diplomaticPoints":-15,"gdpGrowth":-1}', NULL, 'Communists sweep to victory. Washington erupts — \'Who Lost China?\' becomes a weapon. McCarthyism accelerates. Every American ally questions US reliability. Britain and France fear they\'ll be next to be abandoned. The USSR celebrates its greatest ideological victory since 1917. But you saved $2 billion and kept your troops home.');
INSERT INTO crisis_options (crisis_id, country_code, option_key, option_text, cost, effects, military_required, outcome) VALUES (1, 'USSR', 'aid-ccp', '🚩 Major Arms Shipments to Communist Forces', 600, '{"tradeBalance":-600,"diplomaticPoints":12}', '{"army":500000}', 'Soviet weapons flood Manchuria. Mao\'s armies gain decisive firepower advantage. The West watches in alarm — containment is failing. Britain and France worry about communist expansion reaching their colonies. But within the Communist world, Moscow\'s prestige soars. A grateful Mao signs the Sino-Soviet Treaty.');
INSERT INTO crisis_options (crisis_id, country_code, option_key, option_text, cost, effects, military_required, outcome) VALUES (1, 'USSR', 'diplomatic-support', '📢 Cautious Diplomatic Support Only', 100, '{"diplomaticPoints":3,"tradeBalance":-100}', NULL, 'Moscow offers speeches but not guns. Mao wins anyway through sheer numbers and peasant support — but he remembers who actually helped. The seeds of the Sino-Soviet split are planted early. China\'s future communism will be more independent, more unpredictable, and less grateful to Moscow.');
INSERT INTO crisis_options (crisis_id, country_code, option_key, option_text, cost, effects, military_required, outcome) VALUES (1, 'UK', 'protect-hong-kong', '🏰 Reinforce Hong Kong Garrison', 300, '{"tradeBalance":-300,"diplomaticPoints":5}', '{"army":30000}', 'Station troops in Hong Kong as civil war rages nearby. The colony becomes a refuge for Nationalist elites and their gold. Whoever wins China will remember British gunboats at their doorstep — but Hong Kong\'s trade position is secured for decades.');
INSERT INTO crisis_options (crisis_id, country_code, option_key, option_text, cost, effects, military_required, outcome) VALUES (1, 'UK', 'commercial-neutrality', '🏪 Maintain Commercial Ties with Both Sides', 0, '{"tradeBalance":200,"diplomaticPoints":-3}', NULL, 'Pragmatic British merchants trade with whoever controls the ports. Profits flow but both sides view Britain as unprincipled. Americans are annoyed at the fence-sitting.');
INSERT INTO crisis_options (crisis_id, country_code, option_key, option_text, cost, effects, military_required, outcome) VALUES (1, 'India', 'non-aligned-mediation', '🕊️ Offer Non-Aligned Mediation', 50, '{"diplomaticPoints":12}', NULL, 'Nehru positions India as the voice of reason between superpowers. Both sides publicly welcome mediation (privately ignoring it). India\'s prestige as leader of the non-aligned world soars. Everyone owes you a favor.');
INSERT INTO crisis_options (crisis_id, country_code, option_key, option_text, cost, effects, military_required, outcome) VALUES (1, 'India', 'focus-domestic', '🏠 Focus on Domestic Challenges', 0, '{"gdpGrowth":0.5}', NULL, 'India has its own problems — partition looms. Stay out of China\'s civil war and focus scarce resources on building the new nation. A pragmatic choice, but a missed opportunity for diplomatic influence.');
INSERT INTO crisis_options (crisis_id, country_code, option_key, option_text, cost, effects, military_required, outcome) VALUES (2, 'India', 'emergency-relief', '🏥 Emergency Relief for Refugees', 800, '{"gdpGrowth":-1.5,"unemployment":3,"diplomaticPoints":10}', NULL, 'You save millions but economy suffers massive strain.');
INSERT INTO crisis_options (crisis_id, country_code, option_key, option_text, cost, effects, military_required, outcome) VALUES (2, 'India', 'military-order', '🪖 Deploy Army to Restore Order', 400, '{"gdpGrowth":-0.8,"unemployment":1.5}', '{"army":500000}', 'Army prevents worst violence in cities but can\'t be everywhere.');
INSERT INTO crisis_options (crisis_id, country_code, option_key, option_text, cost, effects, military_required, outcome) VALUES (2, 'UK', 'financial-aid', '💷 Provide Financial Aid to Both Nations', 400, '{"tradeBalance":-400,"diplomaticPoints":8}', NULL, 'You try to make amends. Both nations appreciate gesture.');
INSERT INTO crisis_options (crisis_id, country_code, option_key, option_text, cost, effects, military_required, outcome) VALUES (2, 'UK', 'rapid-exit', '🏃 Rapid Withdrawal - Cut Losses', 0, '{"diplomaticPoints":-15}', NULL, 'Maximum chaos. Your reputation in tatters.');
INSERT INTO crisis_options (crisis_id, country_code, option_key, option_text, cost, effects, military_required, outcome) VALUES (3, 'Argentina', 'full-nationalization', '🏭 Full Nationalization Program', 1200, '{"gdpGrowth":2,"inflation":8,"unemployment":-2,"tradeBalance":-800}', NULL, 'Workers love you! Economy booms short-term but inflation rising.');
INSERT INTO crisis_options (crisis_id, country_code, option_key, option_text, cost, effects, military_required, outcome) VALUES (3, 'Argentina', 'gradual-reform', '📊 Gradual Economic Reform', 600, '{"gdpGrowth":1,"inflation":3,"unemployment":-1}', NULL, 'More sustainable. British only moderately angry.');
INSERT INTO crisis_options (crisis_id, country_code, option_key, option_text, cost, effects, military_required, outcome) VALUES (3, 'UK', 'negotiate-compensation', '💷 Negotiate Fair Compensation', 0, '{"tradeBalance":400,"diplomaticPoints":5}', NULL, 'Accept nationalization with payment. Railways were losing money anyway.');
INSERT INTO crisis_options (crisis_id, country_code, option_key, option_text, cost, effects, military_required, outcome) VALUES (3, 'UK', 'protest-nationalization', '📢 Protest Illegal Seizure of British Assets', 100, '{"tradeBalance":-200,"diplomaticPoints":-8}', NULL, 'Demand return of assets. Perón refuses and rallies nationalist support. Anglo-Argentine trade deteriorates. But you\'ve set a precedent against uncompensated nationalization.');
INSERT INTO crisis_options (crisis_id, country_code, option_key, option_text, cost, effects, military_required, outcome) VALUES (3, 'USA', 'economic-pressure', '💵 Economic Pressure on Argentina', 200, '{"tradeBalance":-200,"diplomaticPoints":-5}', NULL, 'Try to isolate Perón economically. Backfires - pushes Argentina toward neutrality.');
INSERT INTO crisis_options (crisis_id, country_code, option_key, option_text, cost, effects, military_required, outcome) VALUES (3, 'USA', 'accept-peronism', '🤝 Accept Perón\'s Third Way', 0, '{"diplomaticPoints":3}', NULL, 'Pragmatic acceptance. Argentina remains trading partner despite ideological differences.');
INSERT INTO crisis_options (crisis_id, country_code, option_key, option_text, cost, effects, military_required, outcome) VALUES (4, 'France', 'full-war', '🪖 Full Colonial War', 600, '{"gdpGrowth":-1.5,"tradeBalance":-600,"inflation":5}', '{"army":150000}', 'Fight for 8 years. Massive costs. Defeated at Dien Bien Phu.');
INSERT INTO crisis_options (crisis_id, country_code, option_key, option_text, cost, effects, military_required, outcome) VALUES (4, 'France', 'negotiate-independence', '🤝 Negotiate Vietnamese Independence', 100, '{"gdpGrowth":0.5,"diplomaticPoints":5,"tradeBalance":400}', NULL, 'Accept decolonization. Save resources. Focus on Europe.');
INSERT INTO crisis_options (crisis_id, country_code, option_key, option_text, cost, effects, military_required, outcome) VALUES (4, 'USA', 'fund-french', '💰 Fund French War Effort', 800, '{"tradeBalance":-800}', NULL, 'Pay 80% of costs! They still lose. Sets you up to inherit war.');
INSERT INTO crisis_options (crisis_id, country_code, option_key, option_text, cost, effects, military_required, outcome) VALUES (4, 'USA', 'pressure-decolonization', '🗽 Pressure France to Decolonize', 0, '{"diplomaticPoints":8}', NULL, 'Position yourself as anti-colonial. Helps in Asia.');
INSERT INTO crisis_options (crisis_id, country_code, option_key, option_text, cost, effects, military_required, outcome) VALUES (4, 'India', 'support-independence', '🗣️ Support Vietnamese Independence', 50, '{"diplomaticPoints":10}', NULL, 'Nehru champions anti-colonialism. Leader of non-aligned.');
INSERT INTO crisis_options (crisis_id, country_code, option_key, option_text, cost, effects, military_required, outcome) VALUES (4, 'India', 'quiet-diplomacy', '🤫 Quiet Diplomacy — Avoid Antagonizing France', 0, '{"diplomaticPoints":-2,"tradeBalance":100}', NULL, 'India has just gained independence and needs trade partners. Publicly neutral, privately sympathetic to Ho Chi Minh. France continues purchasing Indian goods. But the non-aligned movement loses a champion.');
INSERT INTO crisis_options (crisis_id, country_code, option_key, option_text, cost, effects, military_required, outcome) VALUES (4, 'USSR', 'aid-viet-minh', '🚩 Provide Aid to Viet Minh', 400, '{"tradeBalance":-400,"diplomaticPoints":5}', NULL, 'Soviet weapons help Ho Chi Minh. Another communist victory in Asia.');
INSERT INTO crisis_options (crisis_id, country_code, option_key, option_text, cost, effects, military_required, outcome) VALUES (4, 'USSR', 'cautious-support', '📢 Cautious Diplomatic Support', 50, '{"diplomaticPoints":3}', NULL, 'Support decolonization publicly without major commitment. Focus resources on Europe.');
INSERT INTO crisis_options (crisis_id, country_code, option_key, option_text, cost, effects, military_required, outcome) VALUES (5, 'USA', 'airlift', '🛫 Berlin Airlift - Supply by air', 500, '{"gdpGrowth":-0.3,"tradeBalance":-500,"diplomaticPoints":10}', '{"airForce":50000}', 'Supply Berlin for 11 months. Stalin backs down. Western resolve proven.');
INSERT INTO crisis_options (crisis_id, country_code, option_key, option_text, cost, effects, military_required, outcome) VALUES (5, 'USA', 'abandon-berlin', '🏳️ Abandon West Berlin', 0, '{"diplomaticPoints":-20}', NULL, 'Berlin falls. Western credibility shattered.');
INSERT INTO crisis_options (crisis_id, country_code, option_key, option_text, cost, effects, military_required, outcome) VALUES (5, 'UK', 'support-airlift', '✈️ Support American Airlift Operation', 200, '{"gdpGrowth":-0.2,"tradeBalance":-200,"diplomaticPoints":8}', '{"airForce":20000}', 'British RAF joins operation. Demonstrates Western unity.');
INSERT INTO crisis_options (crisis_id, country_code, option_key, option_text, cost, effects, military_required, outcome) VALUES (5, 'UK', 'diplomatic-pressure', '🤝 Pursue Diplomatic Channels', 0, '{"diplomaticPoints":3}', NULL, 'Negotiate with Soviets while airlift operates. Moderate success.');
INSERT INTO crisis_options (crisis_id, country_code, option_key, option_text, cost, effects, military_required, outcome) VALUES (5, 'France', 'allow-airlift-access', '✅ Allow Airlift Through French Airspace', 0, '{"diplomaticPoints":6}', NULL, 'French bases critical for supply routes. Strengthens Western ties.');
INSERT INTO crisis_options (crisis_id, country_code, option_key, option_text, cost, effects, military_required, outcome) VALUES (5, 'France', 'limited-support', '⚠️ Reluctant Support - Keep Military Minimal', 0, '{"diplomaticPoints":2}', NULL, 'Allow airlift but avoid military commitment. Domestic criticism.');
INSERT INTO crisis_options (crisis_id, country_code, option_key, option_text, cost, effects, military_required, outcome) VALUES (5, 'USSR', 'maintain-blockade', '🚧 Maintain Blockade', 0, '{"gdpGrowth":-0.4,"diplomaticPoints":-10}', '{"army":500000}', 'If West succeeds with airlift, you lose face.');
INSERT INTO crisis_options (crisis_id, country_code, option_key, option_text, cost, effects, military_required, outcome) VALUES (5, 'USSR', 'negotiate-settlement', '🤝 Negotiate Agreement', 0, '{"diplomaticPoints":5}', NULL, 'Status quo preserved. Shows compromise.');
INSERT INTO crisis_options (crisis_id, country_code, option_key, option_text, cost, effects, military_required, outcome) VALUES (6, 'USA', 'full-marshall', '💵 Full Marshall Plan - $13B', 3250, '{"tradeBalance":-3250,"diplomaticPoints":25}', NULL, 'Western Europe recovers. Win Cold War economically.');
INSERT INTO crisis_options (crisis_id, country_code, option_key, option_text, cost, effects, military_required, outcome) VALUES (6, 'USA', 'reduced-marshall', '📉 Reduced Aid Package - $5B', 1250, '{"tradeBalance":-1250,"diplomaticPoints":10}', NULL, 'Enough to prevent European collapse but not enough for full recovery. Congress is happier. Europe recovers slowly — some nations turn to Soviet trade to fill the gap. Containment is partial.');
INSERT INTO crisis_options (crisis_id, country_code, option_key, option_text, cost, effects, military_required, outcome) VALUES (6, 'UK', 'accept-aid', '✅ Accept Marshall Aid', 0, '{"gdpGrowth":2,"tradeBalance":1200}', NULL, 'Receive $3.2B. Economy recovers.');
INSERT INTO crisis_options (crisis_id, country_code, option_key, option_text, cost, effects, military_required, outcome) VALUES (6, 'UK', 'accept-with-conditions', '🏛️ Accept Aid but Protect Imperial Preference', 0, '{"gdpGrowth":1,"tradeBalance":600,"diplomaticPoints":-5}', NULL, 'Accept aid but insist on preserving Commonwealth trade preferences. Less American money flows in, but Britain keeps its trade bloc intact. Washington is irritated by British exceptionalism.');
INSERT INTO crisis_options (crisis_id, country_code, option_key, option_text, cost, effects, military_required, outcome) VALUES (6, 'France', 'accept-aid', '✅ Accept Marshall Aid', 0, '{"gdpGrowth":2.5,"tradeBalance":1100,"inflation":-5}', NULL, 'Receive $2.7B. Inflation controlled. Boom into 1960s.');
INSERT INTO crisis_options (crisis_id, country_code, option_key, option_text, cost, effects, military_required, outcome) VALUES (6, 'France', 'accept-with-autonomy', '🇫🇷 Accept Aid but Assert French Economic Sovereignty', 0, '{"gdpGrowth":1.5,"tradeBalance":600,"diplomaticPoints":3}', NULL, 'Accept aid on French terms — direct it toward French industrial planning (Monnet Plan) rather than American free-market prescriptions. Less total aid received but greater national control. Seeds of Gaullist independence.');
INSERT INTO crisis_options (crisis_id, country_code, option_key, option_text, cost, effects, military_required, outcome) VALUES (6, 'USSR', 'forbid-satellites', '🚫 Forbid Satellites from Accepting', 0, '{"globalTension":15,"diplomaticPoints":-10}', NULL, 'Iron Curtain descends. East-West split solidifies. Eastern European nations resent being cut off from Western aid.');
INSERT INTO crisis_options (crisis_id, country_code, option_key, option_text, cost, effects, military_required, outcome) VALUES (6, 'USSR', 'counter-offer', '🔴 Launch Molotov Plan — Soviet Counter-Aid', 800, '{"tradeBalance":-800,"diplomaticPoints":8}', NULL, 'Create COMECON to rival Marshall Plan. Subsidize Eastern European economies with Soviet resources. Costly but prevents satellites from looking westward. The socialist economic bloc takes shape.');
INSERT INTO crisis_options (crisis_id, country_code, option_key, option_text, cost, effects, military_required, outcome) VALUES (7, 'USA', 'full-intervention', '🪖 Full Military Intervention', 2500, '{"gdpGrowth":-1.5,"tradeBalance":-2500,"diplomaticPoints":15}', '{"army":300000,"navy":100000,"airForce":100000}', 'Push to 38th parallel. If advance to China border, China intervenes!');
INSERT INTO crisis_options (crisis_id, country_code, option_key, option_text, cost, effects, military_required, outcome) VALUES (7, 'USA', 'accept-unification', '🏳️ Accept Communist Unification', 0, '{"diplomaticPoints":-25}', NULL, 'Catastrophic for credibility. Every ally panics.');
INSERT INTO crisis_options (crisis_id, country_code, option_key, option_text, cost, effects, military_required, outcome) VALUES (7, 'UK', 'full-intervention', '🪖 Participate in UN Military Forces', 500, '{"gdpGrowth":1,"tradeBalance":200,"diplomaticPoints":15}', '{"army":50000,"navy":30000,"airForce":10000}', 'Push to 38th parallel. If advance to China border, China intervenes!');
INSERT INTO crisis_options (crisis_id, country_code, option_key, option_text, cost, effects, military_required, outcome) VALUES (7, 'UK', 'accept-unification', '🏳️ Accept Communist Unification', 0, '{"diplomaticPoints":-25}', NULL, 'Catastrophic for credibility. Every ally panics.');
INSERT INTO crisis_options (crisis_id, country_code, option_key, option_text, cost, effects, military_required, outcome) VALUES (7, 'China', 'enter-war', '🇨🇳 Enter War if USA Approaches Border', 1500, '{"gdpGrowth":-3,"tradeBalance":-1500,"diplomaticPoints":10}', '{"army":1000000}', 'Human wave attacks. Push USA back. Massive casualties but prove China major power.');
INSERT INTO crisis_options (crisis_id, country_code, option_key, option_text, cost, effects, military_required, outcome) VALUES (7, 'China', 'border-defense', '🛡️ Defensive Posture — Protect Border Only', 400, '{"gdpGrowth":-0.5,"tradeBalance":-400,"diplomaticPoints":-5}', '{"army":300000}', 'Mass troops at the Yalu but don\'t cross. If USA stays south of the 38th parallel, China stays out. Avoid catastrophic casualties but appear weak to Moscow. North Korea may fall. Mao\'s prestige within the Communist world suffers — but the Chinese economy is spared.');
INSERT INTO crisis_options (crisis_id, country_code, option_key, option_text, cost, effects, military_required, outcome) VALUES (7, 'India', 'non-aligned-mediation', '🕊️ Offer to Mediate', 50, '{"diplomaticPoints":15}', NULL, 'Establish India as neutral mediator.');
INSERT INTO crisis_options (crisis_id, country_code, option_key, option_text, cost, effects, military_required, outcome) VALUES (7, 'India', 'condemn-aggression', '📢 Condemn North Korean Aggression at UN', 0, '{"diplomaticPoints":5,"tradeBalance":200}', NULL, 'Side with the Western position at the UN Security Council. Gain American goodwill and trade access, but alienate the Soviet bloc and damage India\'s non-aligned credentials. Nehru faces domestic criticism from the left.');
INSERT INTO crisis_options (crisis_id, country_code, option_key, option_text, cost, effects, military_required, outcome) VALUES (7, 'Argentina', 'stay-neutral', '🤷 Remain Neutral', 0, '{"diplomaticPoints":3}', NULL, 'Distant conflict. Focus on domestic issues.');
INSERT INTO crisis_options (crisis_id, country_code, option_key, option_text, cost, effects, military_required, outcome) VALUES (7, 'Argentina', 'sell-supplies', '🌾 Sell Food and Supplies to UN Forces', 0, '{"tradeBalance":500,"diplomaticPoints":5}', NULL, 'War means hungry armies. Argentine beef and grain flow to UN supply lines at premium prices. Profitable neutrality — everyone\'s friend, nobody\'s ally. Perón\'s Third Position in action.');
INSERT INTO crisis_options (crisis_id, country_code, option_key, option_text, cost, effects, military_required, outcome) VALUES (7, 'USSR', 'support-north', '🚩 Provide Weapons and Advisors to North Korea', 800, '{"tradeBalance":-800,"diplomaticPoints":-5}', NULL, 'Soviet MiGs and tanks help North Korea. Risk of direct confrontation with USA.');
INSERT INTO crisis_options (crisis_id, country_code, option_key, option_text, cost, effects, military_required, outcome) VALUES (7, 'USSR', 'limited-involvement', '⚠️ Limited Covert Support', 300, '{"tradeBalance":-300,"diplomaticPoints":2}', NULL, 'Provide some aid while maintaining deniability. Let China take the lead.');
INSERT INTO crisis_options (crisis_id, country_code, option_key, option_text, cost, effects, military_required, outcome) VALUES (7, 'France', 'token-forces', '🪖 Send Token UN Forces', 150, '{"gdpGrowth":-0.2,"tradeBalance":-150,"diplomaticPoints":5}', '{"army":10000}', 'Show solidarity with allies while preserving forces for Indochina.');
INSERT INTO crisis_options (crisis_id, country_code, option_key, option_text, cost, effects, military_required, outcome) VALUES (7, 'France', 'focus-indochina', '🇻🇳 Focus on Indochina Instead', 0, '{"diplomaticPoints":-3}', NULL, 'Already fighting in Vietnam. Cannot commit to Korea. Allies understand... mostly.');
INSERT INTO crisis_options (crisis_id, country_code, option_key, option_text, cost, effects, military_required, outcome) VALUES (8, 'Argentina', 'demand-full-payment', '💰 Demand Full Payment Immediately', 0, '{"tradeBalance":1500,"diplomaticPoints":-8}', NULL, 'Britain cannot pay. Seize British railway assets instead. Relations severely damaged.');
INSERT INTO crisis_options (crisis_id, country_code, option_key, option_text, cost, effects, military_required, outcome) VALUES (8, 'Argentina', 'negotiate-railways', '🚂 Accept Railway Nationalization as Payment', 800, '{"gdpGrowth":1.5,"tradeBalance":-800,"diplomaticPoints":5}', NULL, 'Take control of British-owned railways. Fair deal - maintain relations.');
INSERT INTO crisis_options (crisis_id, country_code, option_key, option_text, cost, effects, military_required, outcome) VALUES (8, 'Argentina', 'extend-credit', '🤝 Extend Credit Terms to Britain', 0, '{"tradeBalance":-500,"diplomaticPoints":15}', NULL, 'Generous gesture. Britain grateful. Strengthens Argentine influence in Europe.');
INSERT INTO crisis_options (crisis_id, country_code, option_key, option_text, cost, effects, military_required, outcome) VALUES (8, 'UK', 'offer-railways', '🚂 Offer Railway Assets as Payment', 0, '{"tradeBalance":400,"diplomaticPoints":3}', NULL, 'Railways were losing money anyway. Fair settlement.');
INSERT INTO crisis_options (crisis_id, country_code, option_key, option_text, cost, effects, military_required, outcome) VALUES (8, 'UK', 'request-us-loan', '💵 Request US Loan to Pay Argentina', 200, '{"tradeBalance":-200,"diplomaticPoints":-5}', NULL, 'More dependence on USA. Argentina gets paid but British prestige suffers.');
INSERT INTO crisis_options (crisis_id, country_code, option_key, option_text, cost, effects, military_required, outcome) VALUES (8, 'USA', 'pressure-argentina', '⚠️ Pressure Argentina to Forgive Debt', 100, '{"diplomaticPoints":-10}', NULL, 'Perón refuses. \'Yankees go home!\' Latin American solidarity against US.');
INSERT INTO crisis_options (crisis_id, country_code, option_key, option_text, cost, effects, military_required, outcome) VALUES (8, 'USA', 'stay-out', '🤷 Stay Out of Bilateral Dispute', 0, '{"diplomaticPoints":3}', NULL, 'Not your problem. Let them sort it out.');
INSERT INTO crisis_options (crisis_id, country_code, option_key, option_text, cost, effects, military_required, outcome) VALUES (9, 'Argentina', 'maximize-prices', '📈 Maximize Export Prices', 0, '{"gdpGrowth":3,"tradeBalance":2500,"diplomaticPoints":-15}', NULL, 'Huge profits! But Europe resents you. USA accuses Argentina of profiteering.');
INSERT INTO crisis_options (crisis_id, country_code, option_key, option_text, cost, effects, military_required, outcome) VALUES (9, 'Argentina', 'fair-prices', '⚖️ Offer Fair Prices to Europe', 500, '{"gdpGrowth":1.5,"tradeBalance":1200,"diplomaticPoints":10}', NULL, 'Good profits AND goodwill. Spain especially grateful.');
INSERT INTO crisis_options (crisis_id, country_code, option_key, option_text, cost, effects, military_required, outcome) VALUES (9, 'Argentina', 'food-aid', '🍞 Provide Food Aid to Devastated Nations', 1000, '{"gdpGrowth":0.5,"tradeBalance":500,"diplomaticPoints":20}', NULL, 'Evita\'s charitable image extended to foreign policy. Huge popularity.');
INSERT INTO crisis_options (crisis_id, country_code, option_key, option_text, cost, effects, military_required, outcome) VALUES (9, 'USA', 'compete-prices', '🌽 Compete with Lower Prices', 800, '{"tradeBalance":-800,"diplomaticPoints":10}', NULL, 'Undercut Argentina. Europe grateful but American farmers unhappy.');
INSERT INTO crisis_options (crisis_id, country_code, option_key, option_text, cost, effects, military_required, outcome) VALUES (9, 'USA', 'let-market-decide', '📊 Let Market Set Prices', 0, '{"tradeBalance":1500,"diplomaticPoints":-5}', NULL, 'Profits flow. But accused of not helping starving Europeans.');
INSERT INTO crisis_options (crisis_id, country_code, option_key, option_text, cost, effects, military_required, outcome) VALUES (9, 'UK', 'buy-argentine', '🇦🇷 Accept Argentine Terms', 600, '{"tradeBalance":-600,"diplomaticPoints":3}', NULL, 'Feed your people. Swallow pride.');
INSERT INTO crisis_options (crisis_id, country_code, option_key, option_text, cost, effects, military_required, outcome) VALUES (9, 'UK', 'seek-us-aid', '🇺🇸 Seek US Food Aid Instead', 0, '{"diplomaticPoints":-3}', NULL, 'Marshall Plan provides food. More dependent on USA.');
INSERT INTO crisis_options (crisis_id, country_code, option_key, option_text, cost, effects, military_required, outcome) VALUES (9, 'France', 'bilateral-deal', '🤝 Negotiate Bilateral Deal with Argentina', 400, '{"tradeBalance":-400,"diplomaticPoints":5}', NULL, 'Wine and culture for beef and grain. Mutual respect.');
INSERT INTO crisis_options (crisis_id, country_code, option_key, option_text, cost, effects, military_required, outcome) VALUES (9, 'France', 'colonial-agriculture', '🌍 Expand Colonial Agricultural Production', 300, '{"tradeBalance":200,"gdpGrowth":0.5,"diplomaticPoints":-5}', NULL, 'Intensify food production in North Africa and Indochina. Reduce dependency on Argentine imports. Colonial subjects bear the cost — forced labor quotas increase. Effective but morally costly, and fuels independence movements.');
INSERT INTO crisis_options (crisis_id, country_code, option_key, option_text, cost, effects, military_required, outcome) VALUES (9, 'India', 'solidarity', '🤝 Express Solidarity with Argentina\'s Position', 0, '{"diplomaticPoints":8}', NULL, 'Developing nations should control their resources! Third World unity.');
INSERT INTO crisis_options (crisis_id, country_code, option_key, option_text, cost, effects, military_required, outcome) VALUES (9, 'India', 'export-competition', '🌾 Compete as Alternative Grain Exporter', 200, '{"tradeBalance":400,"gdpGrowth":0.5,"diplomaticPoints":3}', NULL, 'India has vast farmland. Redirect some domestic production to export at prices below Argentina\'s. European buyers welcome the competition. Indian farmers earn more, but domestic food security tightens.');
INSERT INTO crisis_options (crisis_id, country_code, option_key, option_text, cost, effects, military_required, outcome) VALUES (10, 'Argentina', 'austerity', '📉 Implement Austerity Measures', 0, '{"gdpGrowth":-2,"inflation":-3,"unemployment":2,"diplomaticPoints":-5}', NULL, 'Cut spending. Unions furious. Peronist base cracks.');
INSERT INTO crisis_options (crisis_id, country_code, option_key, option_text, cost, effects, military_required, outcome) VALUES (10, 'Argentina', 'borrow-abroad', '💵 Seek Foreign Loans', 0, '{"gdpGrowth":0.5,"tradeBalance":-800,"diplomaticPoints":-8}', NULL, 'Compromise Third Position principles. IMF conditions hurt sovereignty.');
INSERT INTO crisis_options (crisis_id, country_code, option_key, option_text, cost, effects, military_required, outcome) VALUES (10, 'Argentina', 'maintain-spending', '💪 Maintain Social Spending Despite Crisis', 1200, '{"gdpGrowth":-1,"inflation":8,"unemployment":-1,"diplomaticPoints":5}', NULL, 'Print money to fund programs. Workers love you. Inflation soars.');
INSERT INTO crisis_options (crisis_id, country_code, option_key, option_text, cost, effects, military_required, outcome) VALUES (10, 'USA', 'offer-aid', '🤝 Offer Emergency Food Aid', 400, '{"tradeBalance":-400,"diplomaticPoints":15}', NULL, 'Extend olive branch. Perón reluctantly accepts. Relations improve.');
INSERT INTO crisis_options (crisis_id, country_code, option_key, option_text, cost, effects, military_required, outcome) VALUES (10, 'USA', 'exploit-weakness', '📉 Demand Political Concessions for Aid', 0, '{"diplomaticPoints":-10}', NULL, 'Perón refuses. \'We would rather starve!\' Latin America rallies to Argentina.');
INSERT INTO crisis_options (crisis_id, country_code, option_key, option_text, cost, effects, military_required, outcome) VALUES (10, 'UK', 'return-favor', '🍞 Return the Favor — Send Food to Argentina', 300, '{"tradeBalance":-300,"diplomaticPoints":12}', NULL, 'Remember when Argentina fed us? Time to repay. Relations healed.');
INSERT INTO crisis_options (crisis_id, country_code, option_key, option_text, cost, effects, military_required, outcome) VALUES (10, 'UK', 'exploit-leverage', '📊 Use Argentine Weakness to Renegotiate Trade Terms', 0, '{"tradeBalance":300,"diplomaticPoints":-10}', NULL, 'Argentina is desperate — demand better terms on beef and grain contracts. Short-term profits, but Perón will remember this betrayal. Future Anglo-Argentine trade suffers.');
INSERT INTO crisis_options (crisis_id, country_code, option_key, option_text, cost, effects, military_required, outcome) VALUES (11, 'Argentina', 'state-funeral', '⚰️ Grand State Funeral and National Mourning', 500, '{"gdpGrowth":-0.5,"diplomaticPoints":10}', NULL, 'Millions mourn. Evita becomes eternal symbol. Movement unified in grief.');
INSERT INTO crisis_options (crisis_id, country_code, option_key, option_text, cost, effects, military_required, outcome) VALUES (11, 'Argentina', 'foundation-continues', '🏥 Foundation Continues Her Work', 800, '{"gdpGrowth":-0.3,"unemployment":-1,"diplomaticPoints":8}', NULL, 'Her legacy lives on. Social programs maintained. Workers remember.');
INSERT INTO crisis_options (crisis_id, country_code, option_key, option_text, cost, effects, military_required, outcome) VALUES (11, 'Argentina', 'political-reform', '🔄 Begin Political Reforms', 200, '{"gdpGrowth":0.5,"diplomaticPoints":5}', NULL, 'Use moment for reconciliation. Opposition cautiously optimistic.');
INSERT INTO crisis_options (crisis_id, country_code, option_key, option_text, cost, effects, military_required, outcome) VALUES (11, 'USA', 'condolences', '💐 Send Official Condolences', 0, '{"diplomaticPoints":5}', NULL, 'Diplomatic gesture. Maybe relations can improve now.');
INSERT INTO crisis_options (crisis_id, country_code, option_key, option_text, cost, effects, military_required, outcome) VALUES (11, 'USA', 'exploit-instability', '🕵️ Quietly Cultivate Anti-Perón Opposition', 200, '{"diplomaticPoints":-8,"tradeBalance":-200}', NULL, 'With Evita gone, Perón\'s coalition may fracture. CIA contacts Argentine military officers and business leaders. If discovered, relations collapse entirely. But if it works, Argentina may realign toward Washington within a few years.');
INSERT INTO crisis_options (crisis_id, country_code, option_key, option_text, cost, effects, military_required, outcome) VALUES (11, 'UK', 'condolences', '💐 Send Royal Condolences', 0, '{"diplomaticPoints":5}', NULL, 'Even former enemies respect grief. Relations warming.');
INSERT INTO crisis_options (crisis_id, country_code, option_key, option_text, cost, effects, military_required, outcome) VALUES (11, 'UK', 'trade-overture', '🤝 Propose New Anglo-Argentine Trade Agreement', 100, '{"tradeBalance":300,"diplomaticPoints":3}', NULL, 'With Evita\'s populist fire gone, Perón may be more pragmatic. Propose comprehensive trade deal while the political landscape shifts. Argentine beef for British manufactures — rebuild the old commercial relationship.');

-- Total rows inserted: 90
